### ISSUE TITLE
Objenesis can't work on the Google Apps Engine

### ISSUE THREAD

**Issue by henri-tremblay** [easymock/objenesis#15]
Original [issue 12](https://code.google.com/p/objenesis/issues/detail?id=12) created by henri-tremblay on 2010-10-09T10:34:41.000Z:

Trying to use objenesis on GAE the following exception is thrown

java.lang.NoClassDefFoundError: sun.reflect.ReflectionFactory is a restricted class. 
Please see the Google  App Engine developer's guide for more details.
at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:51)
at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.&lt;init&gt;(SunReflectionFactoryInstantiator.java:40)
at org.objenesis.strategy.StdInstantiatorStrategy.newInstantiatorOf(StdInstantiatorStrategy.java:85)
at org.objenesis.ObjenesisBase.getInstantiatorOf(ObjenesisBase.java:90)
at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)

**Comment by henri-tremblay** [comment]
No perfect solution seems possible so far. I've implemented the best I could so far https://github.com/easymock/objenesis/blob/master/SupportedJVMs.md
