### ISSUE TITLE
Test errors with Java 10

### ISSUE THREAD

**Issue by ebourg** [easymock/objenesis#59]
Hi,

There are two test errors with Java 10:
```
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.053 sec <<< FAILURE! - in org.objenesis.instantiator.sun.MagicInstantiatorTest
testInternalInstantiator(org.objenesis.instantiator.sun.MagicInstantiatorTest)  Time elapsed: 0.014 sec  <<< ERROR!
java.lang.IllegalAccessError: class org.objenesis.instantiator.sun.MagicInstantiator$$$EmptyClass loaded by jdk/internal/loader/ClassLoaders$AppClassLoader cannot access jdk/internal/reflect superclass jdk.internal.reflect.MagicAccessorImpl
        at org.objenesis.instantiator.sun.MagicInstantiatorTest.testInternalInstantiator(MagicInstantiatorTest.java:51)

testNewInstance(org.objenesis.instantiator.sun.MagicInstantiatorTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.IllegalAccessError: class org.objenesis.instantiator.sun.MagicInstantiator$$$EmptyClass loaded by jdk/internal/loader/ClassLoaders$AppClassLoader cannot access jdk/internal/reflect superclass jdk.internal.reflect.MagicAccessorImpl
        at org.objenesis.instantiator.sun.MagicInstantiatorTest.testNewInstance(MagicInstantiatorTest.java:42)
```

**Comment by henri-tremblay** [comment]
Interesting. Thanks. Yes. The Magic concept was indeed removed so this test should be ignored to Java 10.

**Comment by ebourg** [comment]
Thank you for the quick fix.
